feat(LGDI-21): update PR.yml

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -1,28 +1,28 @@
 name: PR pipeline
 
 on:
-  pull_request:
+  # Trigger the workflow on pull request
+  pull_request
 
 permissions:
   contents: write
   issues: write
   pull-requests: write
-  security-events: write   # REQUIRED for SARIF uploads
 
 jobs:
   pr:
     runs-on: ubuntu-latest
     timeout-minutes: 60
-
     steps:
+      # Setup
       - name: ⚙️ Checkout Code
-        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
 
       - name: ⚙️ Setup Terraform
-        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
+        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
 
       - name: ⚙️ Setup Node.js
-        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
+        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
         with:
           node-version-file: '.node-version'
 
@@ -32,49 +32,66 @@ jobs:
       - name: ⚙️ Validate Typescript
         run: npm run build:validate
 
+      # Formatting
+      - name: 📝 Run Lint
+        run: npm run lint
+
       - name: 📝 Terraform naming convention lint
         run: npm run development:organize:tf -- --dry-run
 
       - name: Terraform init (no backend)
-        working-directory: ./terraform/
+        working-directory: ./terraform/notifications
         run: terraform init -backend=false
 
       - name: 📝 Terraform Formatting
-        working-directory: ./terraform/
+        working-directory: ./terraform/notifications
         run: terraform fmt -check -diff -recursive
 
       - name: 📝 Terraform validate
-        working-directory: ./terraform/
+        working-directory: ./terraform/notifications
         run: terraform validate
 
-      # -----------------------------
-      # 🔒 tfsec with inline PR comments
-      # -----------------------------
-      - name: Run tfsec (SARIF output)
+      # Testing
+      - name: 🧪 Run Unit tests
+        id: unittests
         run: |
-          mkdir -p reports
-          tfsec --format sarif --out reports/tfsec.sarif ./terraform
+          echo "Test results:" > coverage.md
+          echo '```' >> coverage.md
+          (npm run test:coverage 2>&1 | grep -A1000 "= Coverage summary =" | tee -a coverage.md) || echo "Failed to meet the criteria"
+          echo '```' >> coverage.md
+          content="${content//'%'/'%25'}"
+          content="${content//$'\n'/'%0A'}"
+          content="${content//$'\r'/'%0D'}"
 
-      - name: Upload tfsec SARIF to GitHub
-        uses: github/codeql-action/upload-sarif@v3
+          echo 'report<<EOF' >> $GITHUB_OUTPUT
+          cat coverage.md >> $GITHUB_OUTPUT
+          echo 'EOF' >> $GITHUB_OUTPUT
+
+      - name: 🧪 Create Comment with Test results
+        uses: hasura/comment-progress@146c635f3e325d478025e29e5043ec1c07c0e36c # v2.3.0
         with:
-          sarif_file: reports/tfsec.sarif
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          repository: 'govuk-once/gds-unified-notification-service'
+          number: ${{ github.event.number }}
+          id: unittestscomment
+          message: '${{steps.unittests.outputs.report}}'
+          recreate: true
 
-      # -----------------------------
-      # 🔒 checkov with inline PR comments
-      # -----------------------------
-      - name: Run checkov (SARIF output)
-        run: |
-          mkdir -p reports
-          checkov -d ./terraform --output sarif --output-file-path reports/checkov.sarif
+      # Security scans - Always executed even if the formatting or tests fail
+      - name: 🔐 TF Sec
+        if: success() || failure()
+        uses: aquasecurity/tfsec-action@a73ebc46fba54691e25cbe901656e7b205fb9bf2 # v1.0.0
 
-      - name: Upload checkov SARIF to GitHub
-        uses: github/codeql-action/upload-sarif@v3
+      - name: 🔐 Checkov GitHub Action
+        if: success() || failure()
+        uses: bridgecrewio/checkov-action@8f61ce5b8a3afb4ca94d236b75201878ded6d2cd # v12
         with:
-          sarif_file: reports/checkov.sarif
+          output_format: cli,sarif
+          output_file_path: console,results.sarif
+          soft_fail: true
 
-      # -----------------------------
-      # 🧪 Unit tests
-      # -----------------------------
-      - name: Run unit tests
-        run: npm test -- --run
+      - name: ⚙️ Upload SARIF file
+        uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4
+        if: success() || failure()
+        with:
+          sarif_file: results.sarif
